# Generated by Django 5.1 on 2024-08-13 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loginify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='Username',
            new_name='username',
        ),
    ]
